apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bookinfo-ingress-user01
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
  - host: "bookinfo.yjsong.cloud.35.209.207.26.nip.io"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: istio-ingressgateway
            port:
              number: 80
